replicaCount: 1

image:
  repository: httpd
  tag: "2.4"

service:
  type: ClusterIP

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: false
