apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app: nginx
            chart: nginx
            version: "18.3.5"
          - app: apache
            chart: apache
            version: "11.3.4"
  template:
    metadata:
      name: "dev-{{app}}"
      namespace: argocd
      labels:
        app: "{{app}}"
        env: dev
    spec:
      project: default
      sources:
        - repoURL: registry-1.docker.io/techino
          chart: "{{chart}}"
          targetRevision: "{{version}}"
          helm:
            releaseName: "{{app}}"
            valueFiles:
              - "$values/envs/dev/{{app}}/values.yaml"
        - repoURL: https://github.com/AlexyPulivelil/work-gitops.git
          targetRevision: HEAD
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: apps-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
