repoURL: https://github.com/AlexyPulivelil/work-gitops.git
targetRevision: HEAD
valuesPath: envs/dev
registry: registry-1.docker.io/techino
namespace: apps-dev

# Common defaults applied to ALL apps. Override per-app in apps.yaml under values:
defaults:
  replicaCount: 1
